site: mayankj.github.io
url: 
author:
  name: Mayank Jain
  email: mjain30312@gmail.com 
  url: 
  avatar: 
title: mayankj
description: Personal Website/Landing Page
logo: 
image: 
permalink: pretty
projectColor: 

baseurl:             ""

include:
  - _redirects
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - disqus-for-jekyll

collections:
  pages:
    output: true
    permalink: /:name
  projects:
    output: true
    permalink: /projects/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"     
      
  - scope:
      path: "assets/img"
    values:
      image: true
